chore: run build and test on master to normalize workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,26 +1,23 @@
 name: 'Deploy'
 
+# Run the deploy workflow only on master once the Build and Test workflow completes
 on:
-  push:
-    branches: ['master']
+  workflow_run:
+    workflows: ['Build and Test']
+    branches: [master]
+    types: [completed]
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: oven-sh/setup-bun@v1
-        with:
-          bun-version: 1.0.0
+      - name: Fail if Build and Test workflow failed
+        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
+        run: |
+          echo "Build and Test step failed. Not deploying."
+          exit 1
       - uses: actions/checkout@v3
-      - name: Install dependencies
-        run: bun i
-      - name: Check formatting
-        run: bun run check-format
-      - name: Build
-        run: bun run build
-      - name: Run unit tests
-        run: bun run test
       - name: Set environment variables
         run: export AWS_PAGER=
       - name: Configure AWS Credentials
